<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" data-theme="dark">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="theme-color" content="#0ea5e9">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <meta name="apple-mobile-web-app-title" content="CargoOS">
    <meta name="application-name" content="CargoOS">
    <meta name="msapplication-TileColor" content="#0f1117">
    <meta name="msapplication-TileImage" content="/icons/icon-144.png">

    <title>CargoOS — RT Express</title>

    {{-- Favicons --}}
    <link rel="icon" type="image/svg+xml" href="/favicon.svg">
    <link rel="icon" type="image/x-icon" href="/favicon.ico">
    <link rel="apple-touch-icon" sizes="180x180" href="/icons/icon-180.png">

    {{-- PWA Manifest (generated by vite-plugin-pwa) --}}
    <link rel="manifest" href="/build/manifest.webmanifest">

    @viteReactRefresh
    @vite(['resources/css/app.css', 'resources/js/app.tsx'])

    {{-- PWA service worker registration --}}
    <script>
        if ('serviceWorker' in navigator) {
            window.addEventListener('load', () => {
                navigator.serviceWorker.register('/build/sw.js', { scope: '/' })
                    .catch(() => {}); // silently ignore errors in dev
            });
        }
    </script>
</head>
<body>
    <div id="app"></div>
</body>
</html>
